/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.109
 * Generated at: 2025-09-10 15:23:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.register;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.srm.hms.model.Users;

public final class register_002dupdate_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2 1.jar", Long.valueOf(1757245690243L));
    _jspx_dependants.put("jar:file:/D:/HospitalManagementSystem/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/HospitalManagementSystem/WEB-INF/lib/jstl-1.2%201.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("com.srm.hms.model.Users");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Update User Details</title>\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\"\r\n");
      out.write("        integrity=\"sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T\"\r\n");
      out.write("        crossorigin=\"anonymous\">\r\n");
      out.write("    <style>\r\n");
      out.write("        body {\r\n");
      out.write("            background-image: url('https://www.business2community.com/wp-content/uploads/2024/04/biggest-ecommerce-companies-featured-image.png');\r\n");
      out.write("            background-repeat: no-repeat;\r\n");
      out.write("            background-position: center;\r\n");
      out.write("            background-size: cover;\r\n");
      out.write("            color: #333;\r\n");
      out.write("        }\r\n");
      out.write("        .card {\r\n");
      out.write("            border-radius: 20px;\r\n");
      out.write("            background: rgba(255, 255, 255, 0.9);\r\n");
      out.write("        }\r\n");
      out.write("        .card-body {\r\n");
      out.write("            padding: 2rem;\r\n");
      out.write("        }\r\n");
      out.write("        .btn-update {\r\n");
      out.write("            background-color: #007bff;\r\n");
      out.write("            border-color: #007bff;\r\n");
      out.write("        }\r\n");
      out.write("        .btn-update:hover {\r\n");
      out.write("            background-color: #0056b3;\r\n");
      out.write("            border-color: #004085;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    ");

        Users userRole = (Users) session.getAttribute("user");
        if ("Admin".equals(userRole.getUser_role())) {
            request.getRequestDispatcher("/Admin/AdminHeader.jsp").include(request, response);
        } else {
            request.getRequestDispatcher("/Customer/CustomerHeader.jsp").include(request, response);
        }
    
      out.write("\r\n");
      out.write("          <br>\r\n");
      out.write("                    <br>\r\n");
      out.write("                    <br>\r\n");
      out.write("                    <br>\r\n");
      out.write("    <div class=\"container mt-4\">\r\n");
      out.write("        <div class=\"row justify-content-center\">\r\n");
      out.write("            <div class=\"col-md-6\">\r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("           \r\n");
      out.write("                        <h1 class=\"card-title mb-4\">User Details</h1>\r\n");
      out.write("                        <form action=\"");
      out.print(request.getContextPath());
      out.write("/profile\" method=\"post\">\r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("                                <label for=\"user_firstName\">First Name:</label>\r\n");
      out.write("                                <input type=\"text\" id=\"user_firstName\" value=\"");
      out.print(userRole.getUser_firstName());
      out.write("\"\r\n");
      out.write("                                    class=\"form-control\" name=\"user_firstName\" required>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("                                <label for=\"user_lastName\">Last Name:</label>\r\n");
      out.write("                                <input type=\"text\" id=\"user_lastName\" value=\"");
      out.print(userRole.getUser_lastName());
      out.write("\"\r\n");
      out.write("                                    class=\"form-control\" name=\"user_lastName\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("                                <label for=\"user_role\">Role:</label>\r\n");
      out.write("                                <input type=\"text\" id=\"user_role\" value=\"");
      out.print(userRole.getUser_role());
      out.write("\"\r\n");
      out.write("                                    class=\"form-control\" name=\"user_role\" readonly>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("                                <label for=\"user_email\">Email:</label>\r\n");
      out.write("                                <input type=\"email\" id=\"user_email\" value=\"");
      out.print(userRole.getUser_email());
      out.write("\"\r\n");
      out.write("                                    class=\"form-control\" name=\"user_email\" readonly>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("                                <label for=\"user_mobile_number\">Mobile Number:</label>\r\n");
      out.write("                                <input type=\"tel\" id=\"user_mobile_number\" value=\"");
      out.print(userRole.getUser_mobile_number());
      out.write("\"\r\n");
      out.write("                                    class=\"form-control\" name=\"user_mobile_number\" required>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("                                <label for=\"user_password\">Password:</label>\r\n");
      out.write("                                <input type=\"password\" id=\"user_password\" value=\"");
      out.print(userRole.getUser_password());
      out.write("\"\r\n");
      out.write("                                    class=\"form-control\" name=\"user_password\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <button type=\"submit\" class=\"btn btn-update\">Update</button>\r\n");
      out.write("                        </form>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <br>\r\n");
      out.write("    <script>\r\n");
      out.write("        // Function to get query parameters\r\n");
      out.write("        function getQueryParam(param) {\r\n");
      out.write("            const urlParams = new URLSearchParams(window.location.search);\r\n");
      out.write("            return urlParams.get(param);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        // Check if the \"success\" query parameter is present\r\n");
      out.write("        const success = getQueryParam('success');\r\n");
      out.write("\r\n");
      out.write("        if (success === 'true') {\r\n");
      out.write("            alert('Profile updated successfully!.. Now go to the profile page .');\r\n");
      out.write("        } else if (success === 'false') {\r\n");
      out.write("            alert('Failed to update profile. Please try again.');\r\n");
      out.write("        }\r\n");
      out.write("    </script>\r\n");
      out.write("    \r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/footer.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
